# Generated by Django 4.1.5 on 2023-01-20 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_alter_teachersalary_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teachersalary',
            old_name='amount',
            new_name='paid_amount',
        ),
        migrations.AddField(
            model_name='teachersalary',
            name='payment_ref',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teachersalary',
            name='salary_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
