# Generated by Django 4.1.5 on 2023-01-25 09:41

from django.db import migrations, models
import payment.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # migrations.CreateModel(
        #     name='IncampusPayments',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('created_at', models.DateTimeField(auto_now_add=True)),
        #         ('updated_at', models.DateTimeField(auto_now_add=True)),
        #         ('payment_ref', models.CharField(default=payment.models.generate_payment_refno, max_length=50)),
        #         ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
        #         ('invoice_no', models.CharField(blank=True, max_length=255, null=True)),
        #         ('payment_mode', models.CharField(blank=True, max_length=255, null=True)),
        #         ('amount_paid', models.FloatField()),
        #         ('status', models.CharField(blank=True, max_length=50, null=True)),
        #         ('reason', models.CharField(blank=True, max_length=255, null=True)),
        #         # ('payment_from', models.JSONField(blank=True, null=True)),
        #         # ('payment_to', models.JSONField(blank=True, null=True)),
        #         ('isallocated', models.BooleanField(default=False)),
        #         ('notes', models.TextField(blank=True, max_length=255, null=True)),
        #     ],
        #     options={
        #         'abstract': False,
        #     },
        # ),
    ]
