# Generated by Django 4.1.5 on 2023-01-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='incampuspayments',
        #     name='payment_from',
        #     field=models.TextField(blank=True, null=True),
        # ),
        # migrations.AlterField(
        #     model_name='incampuspayments',
        #     name='payment_to',
        #     field=models.TextField(blank=True, null=True),
        # ),
    ]
