# Generated by Django 4.1.5 on 2023-01-19 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('range', models.CharField(blank=True, max_length=50, null=True)),
                ('mark_from', models.IntegerField(blank=True, null=True)),
                ('mark_to', models.IntegerField(blank=True, null=True)),
                ('mark_grade', models.CharField(blank=True, max_length=50, null=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade.grade')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
