# Generated by Django 4.1.5 on 2023-01-20 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_alter_teachersalary_teacher'),
        ('grade', '0002_examgrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grade.grade'),
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_fee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.incampusteacher'),
        ),
    ]
