# Generated by Django 4.1.5 on 2023-01-20 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_alter_teachersalary_teacher'),
        ('grade', '0004_remove_subject_grade_remove_subject_subject_fee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('schedule_day', models.CharField(blank=True, max_length=50, null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade.classroom')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade.grade')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.incampusteacher')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
