# Generated by Django 4.1.5 on 2023-01-24 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_rename_amount_teachersalary_paid_amount_and_more'),
        ('grade', '0005_dailytimetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncampusExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, default='Active', max_length=255, null=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade.grade')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExamSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('exam_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('max_marks', models.IntegerField(blank=True, null=True)),
                ('exam_status', models.CharField(blank=True, default='Pending', max_length=255, null=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade.classroom')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade.incampusexam')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade.subject')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.incampusteacher')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
