# Generated by Django 4.1.5 on 2023-02-13 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0006_incampusexam_examschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='status',
            field=models.CharField(blank=True, default='Active', max_length=255, null=True),
        ),
    ]
