# Generated by Django 4.1.5 on 2023-01-31 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofile', '0003_incampususer_address_incampususer_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncampusFriend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, default='Active', max_length=50, null=True)),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incampus_friend', to='userprofile.incampususer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incampus_user', to='userprofile.incampususer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
