# Generated by Django 4.1.5 on 2023-02-18 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incampusfriend',
            name='friend',
        ),
        migrations.AddField(
            model_name='incampusfriend',
            name='friend_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='incampusfriend',
            name='friend_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
