# Generated by Django 4.1.5 on 2023-02-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_remove_incampusfriend_friend_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incampusfriend',
            name='friend_id',
        ),
        migrations.AddField(
            model_name='incampusfriend',
            name='friend',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='incampusfriend',
            name='friend_type',
            field=models.CharField(default='admin', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='incampusfriend',
            name='user',
            field=models.CharField(max_length=50),
        ),
    ]
