# Generated by Django 4.1.5 on 2023-02-18 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_incampususer_about_me_incampususer_city_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friends', '0003_remove_incampusfriend_friend_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incampusfriend',
            name='friend_type',
        ),
        migrations.AlterField(
            model_name='incampusfriend',
            name='friend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incampus_friend', to='userprofile.incampususer'),
        ),
        migrations.AlterField(
            model_name='incampusfriend',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incampus_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
