# Generated by Django 4.1.5 on 2023-02-18 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friends', '0004_remove_incampusfriend_friend_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incampusfriend',
            name='friend_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='incampusfriend',
            name='friend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incampus_friend', to=settings.AUTH_USER_MODEL),
        ),
    ]
