# Generated by Django 4.1.5 on 2023-02-18 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0005_incampusfriend_friend_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incampusfriend',
            name='status',
            field=models.CharField(blank=True, default='Pending', max_length=50, null=True),
        ),
    ]
