# Generated by Django 4.1.5 on 2023-02-18 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0006_alter_incampusfriend_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='incampusfriend',
            name='user_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
