# Generated by Django 4.1.5 on 2023-01-31 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incampusevent',
            name='category',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='incampusevent',
            name='target',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
