# Generated by Django 4.1.5 on 2023-01-31 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_incampususer_address_incampususer_gender_and_more'),
        ('event', '0002_incampusevent_category_incampusevent_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='incampusevent',
            name='status',
            field=models.CharField(blank=True, default='Active', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='IncampusNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('isread', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.incampusevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.incampususer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
