# Generated by Django 4.1.5 on 2023-01-19 08:42

from django.db import migrations, models
import userprofile.models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incampususer',
            name='profilepic',
            field=models.FileField(blank=True, null=True, upload_to=userprofile.models.user_directory_path),
        ),
    ]
