# Generated by Django 4.1.5 on 2023-01-19 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_incampususer_profilepic'),
    ]

    operations = [
        migrations.AddField(
            model_name='incampususer',
            name='address',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incampususer',
            name='gender',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='incampususer',
            name='phone_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
