# Generated by Django 4.1.5 on 2023-01-20 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('month', models.CharField(blank=True, max_length=50, null=True)),
                ('year', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, default='Active', max_length=50, null=True)),
                ('amount_due', models.FloatField(blank=True, null=True)),
                ('amount_paid', models.FloatField(blank=True, null=True)),
                ('payment_ref', models.CharField(blank=True, max_length=50, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.incampusstudent')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
