# Generated by Django 4.1.5 on 2023-01-21 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_incampusparent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incampusparent',
            name='child',
            field=models.ManyToManyField(blank=True, null=True, to='student.incampusstudent'),
        ),
    ]
