# Generated by Django 4.1.5 on 2023-01-24 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0006_incampusexam_examschedule'),
        ('student', '0005_alter_incampusparent_child'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentExamMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('marks_obtained', models.IntegerField()),
                ('remarks', models.TextField(blank=True, max_length=255, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade.examschedule')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.incampusstudent')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
