# Generated by Django 4.1.5 on 2023-01-24 06:40

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '0003_rename_amount_teachersalary_paid_amount_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('student', '0005_alter_incampusparent_child'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncampusAttendance',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('incampus_type', models.CharField(blank=True, max_length=50, null=True)),
                ('attendance_datetime', models.DateTimeField(blank=True, null=True)),
                ('month', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=50)),
                ('attendance_type', models.CharField(blank=True, max_length=50, null=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.incampusstudent')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.incampusteacher')),
            ],
            options={
                'abstract': False,
            },
            bases=('auth.user', models.Model),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
