# Generated by Django 4.1.5 on 2023-01-24 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IncampusAttendance',
        ),
    ]
