# Generated by Django 4.1.5 on 2023-01-24 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '0003_rename_amount_teachersalary_paid_amount_and_more'),
        ('student', '0005_alter_incampusparent_child'),
        ('attendance', '0002_delete_incampusattendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncampusAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('incampus_type', models.CharField(blank=True, max_length=50, null=True)),
                ('attendance_datetime', models.DateTimeField(blank=True, null=True)),
                ('month', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=50)),
                ('attendance_type', models.CharField(blank=True, max_length=50, null=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.incampusstudent')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.incampusteacher')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
